server:
  port: 8099
spring:
  application:
    name: gate-way
  cloud:
    gateway:
      routes:
        - id: order-server
          uri: lb://service-order #lb 是指使用nacos中的负载均衡策略
          predicates:
            - Path=/order-server/** #断言规则 用于路由规则的定义
          filters:
            - StripPrefix=1 #转发之前去掉第一层 /order-server
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos